language: node_js
node_js:
 - "node"
cache:
  directories:
    - "node_modules"
script: 
 - eslint 'src/**'
 - yarn test:coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

